{% set name = "wagtail-feedback" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_feedback-{{ version }}.tar.gz
  sha256: b040de020f32dbee548a8abb289eeecc217a93f8ed3d567d6584e5b2fa8d6961

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.8.0
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - wagtail >=4.2
    - django-filter >=23.2

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(DEBUG=True); django.setup(); import feedback"
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/wagtail-feedback/
  summary: A Django/Wagtail app to easily ask users for feedback.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
